language: node_js

sudo: false

node_js:
  - 10
  - 11

before_install:
  - npm install codecov -g

install:
  - npm install

script:
  - npm run test:coverage
  - npm run build
  - npm run lint

after_success:
  - codecov

notifications:
  email: false
